name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        version: 8.x
 
    - run: npm ci

    - run: npm run eslint
