name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm ci
      - run: npm test

  publish-snap:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo snap install snapcraft --classic
      - run: sudo snap install multipass --edge
      - run: sudo snapcraft
      - run: |
             sudo mkdir .snapcraft
             echo ${{ secrets.SNAPCRAFT_LOGINFILE }} | sudo base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
             sudo snapcraft push *.snap --release stable
