name: Release

jobs:
  publish-snap:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Snap Store
      - run: sudo snap install snapcraft --classic
      - run: snapcraft
      - run: |
             mkdir .snapcraft
             echo ${{ secrets.SNAPCRAFT_LOGINFILE }} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
             snapcraft push *.snap --release stable
